fmdbsamplemix_customStyle=Custom Style
fmdbsamplemix_customStyle.ui.tooltip=Adds custom CSS class names to the element.
fmdbsamplemix_customStyle.customCssClassname=CSS class names
fmdbsamplemix_customStyle.customCssClassname.ui.tooltip=One or more CSS class names to apply to the element.<br/><b>Usage:</b> <i>Add custom classes for styling or layout overrides</i>.
fmdbsamplemix.section.style=Style


